[package]
name = "Clanware-Innovations/justice-sdk"
description = "A Roblox SDK for the Clanware Justice API."
license="MIT"
version = "1.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
include=["lib"]
exclude=["lib/index.d.ts", "sourcemap.json", "lib/init.spec.lua"]

[dev-dependencies]
testez = "roblox/testez@0.4.1"
